/**
 * Grocery Store — 50 realistic products with varied units.
 * Pure structured data — no business-type conditionals.
 */

export type CatalogItem = {
  category: string;
  name: string;
  sku: string;
  price: number;
  costPrice: number;
  taxCode: string;
  unit: string;
  kind: 'physical' | 'service';
  trackQty: boolean;
  qty: number;
  brand?: string;
  description?: string;
  barcode?: string;
  meta?: Record<string, unknown>;
};

export const GROCERY_CATEGORIES = [
  'Staples & Grains',
  'Pulses & Lentils',
  'Spices & Condiments',
  'Cooking Oil',
  'Dairy',
  'Bakery',
  'Beverages',
  'Snacks',
  'Fruits & Vegetables',
  'Frozen Foods',
  'Cleaning Products',
  'Personal Care',
  'Household',
];

export const GROCERY_PRODUCTS: CatalogItem[] = [
  // ── Staples & Grains ──────────────────────────────────────────────────────
  {
    category: 'Staples & Grains',
    name: 'Basmati Rice – Premium (5kg)',
    sku: 'GRC-RICE-BAS-5K',
    barcode: '8901234560001',
    price: 650,
    costPrice: 480,
    taxCode: '1006',
    unit: 'bag',
    kind: 'physical',
    trackQty: true,
    qty: 100,
    brand: 'India Gate',
    meta: { packSize: '5 kg', expiryTracked: false, sellUnit: 'bag' },
  },
  {
    category: 'Staples & Grains',
    name: 'Broken Wheat (Dalia) – 1kg',
    sku: 'GRC-DALIA-1K',
    barcode: '8901234560002',
    price: 65,
    costPrice: 42,
    taxCode: '1006',
    unit: 'kg',
    kind: 'physical',
    trackQty: true,
    qty: 80,
    brand: 'Aashirvaad',
    meta: { packSize: '1 kg', sellUnit: 'kg' },
  },
  {
    category: 'Staples & Grains',
    name: 'Whole Wheat Atta – 10kg',
    sku: 'GRC-ATTA-10K',
    barcode: '8901234560003',
    price: 420,
    costPrice: 310,
    taxCode: '1101',
    unit: 'bag',
    kind: 'physical',
    trackQty: true,
    qty: 60,
    brand: 'Aashirvaad',
    meta: { packSize: '10 kg', sellUnit: 'bag' },
  },
  {
    category: 'Staples & Grains',
    name: 'Maida (Refined Flour) – 1kg',
    sku: 'GRC-MAIDA-1K',
    barcode: '8901234560004',
    price: 45,
    costPrice: 30,
    taxCode: '1101',
    unit: 'kg',
    kind: 'physical',
    trackQty: true,
    qty: 120,
    brand: 'Pillsbury',
    meta: { packSize: '1 kg', sellUnit: 'kg' },
  },
  {
    category: 'Staples & Grains',
    name: 'Sona Masoori Rice – 5kg',
    sku: 'GRC-RICE-SM-5K',
    barcode: '8901234560005',
    price: 380,
    costPrice: 270,
    taxCode: '1006',
    unit: 'bag',
    kind: 'physical',
    trackQty: true,
    qty: 80,
    brand: 'Kohinoor',
    meta: { packSize: '5 kg', sellUnit: 'bag' },
  },
  {
    category: 'Staples & Grains',
    name: 'Besan (Gram Flour) – 500g',
    sku: 'GRC-BESAN-500',
    barcode: '8901234560006',
    price: 55,
    costPrice: 38,
    taxCode: '1102',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 90,
    brand: 'Fortune',
    meta: { packSize: '500 g', sellUnit: 'pcs' },
  },
  {
    category: 'Staples & Grains',
    name: 'Poha (Flattened Rice) – 500g',
    sku: 'GRC-POHA-500',
    barcode: '8901234560007',
    price: 42,
    costPrice: 28,
    taxCode: '1904',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 70,
    meta: { packSize: '500 g', sellUnit: 'pcs' },
  },

  // ── Pulses & Lentils ─────────────────────────────────────────────────────
  {
    category: 'Pulses & Lentils',
    name: 'Toor Dal (Pigeon Peas) – 1kg',
    sku: 'GRC-TDAL-1K',
    barcode: '8901234560008',
    price: 145,
    costPrice: 110,
    taxCode: '0713',
    unit: 'kg',
    kind: 'physical',
    trackQty: true,
    qty: 100,
    brand: 'Tata Sampann',
    meta: { packSize: '1 kg', sellUnit: 'kg' },
  },
  {
    category: 'Pulses & Lentils',
    name: 'Masoor Dal (Red Lentils) – 1kg',
    sku: 'GRC-MDAL-1K',
    barcode: '8901234560009',
    price: 120,
    costPrice: 88,
    taxCode: '0713',
    unit: 'kg',
    kind: 'physical',
    trackQty: true,
    qty: 90,
    brand: 'Tata Sampann',
    meta: { packSize: '1 kg', sellUnit: 'kg' },
  },
  {
    category: 'Pulses & Lentils',
    name: 'Chana Dal (Bengal Gram) – 1kg',
    sku: 'GRC-CDAL-1K',
    barcode: '8901234560010',
    price: 130,
    costPrice: 95,
    taxCode: '0713',
    unit: 'kg',
    kind: 'physical',
    trackQty: true,
    qty: 80,
    brand: 'Tata Sampann',
    meta: { packSize: '1 kg', sellUnit: 'kg' },
  },
  {
    category: 'Pulses & Lentils',
    name: 'Moong Dal (Green Gram) – 500g',
    sku: 'GRC-MOGDAL-500',
    barcode: '8901234560011',
    price: 88,
    costPrice: 65,
    taxCode: '0713',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 70,
    brand: 'Fortune',
    meta: { packSize: '500 g', sellUnit: 'pcs' },
  },
  {
    category: 'Pulses & Lentils',
    name: 'Rajma (Kidney Beans) – 500g',
    sku: 'GRC-RAJMA-500',
    barcode: '8901234560012',
    price: 95,
    costPrice: 68,
    taxCode: '0713',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 60,
    meta: { packSize: '500 g', sellUnit: 'pcs' },
  },

  // ── Spices & Condiments ───────────────────────────────────────────────────
  {
    category: 'Spices & Condiments',
    name: 'Turmeric Powder – 200g',
    sku: 'GRC-TURMERIC-200',
    barcode: '8901234560013',
    price: 52,
    costPrice: 35,
    taxCode: '0910',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 150,
    brand: 'MDH',
    meta: { packSize: '200 g', sellUnit: 'pcs' },
  },
  {
    category: 'Spices & Condiments',
    name: 'Red Chilli Powder – 200g',
    sku: 'GRC-CHILLI-200',
    barcode: '8901234560014',
    price: 62,
    costPrice: 42,
    taxCode: '0910',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 130,
    brand: 'MDH',
    meta: { packSize: '200 g', sellUnit: 'pcs' },
  },
  {
    category: 'Spices & Condiments',
    name: 'Garam Masala – 100g',
    sku: 'GRC-GARAM-100',
    barcode: '8901234560015',
    price: 68,
    costPrice: 45,
    taxCode: '0910',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 100,
    brand: 'MDH',
    meta: { packSize: '100 g', sellUnit: 'pcs' },
  },
  {
    category: 'Spices & Condiments',
    name: 'Cumin Seeds (Jeera) – 100g',
    sku: 'GRC-CUMIN-100',
    barcode: '8901234560016',
    price: 45,
    costPrice: 30,
    taxCode: '0909',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 120,
    meta: { packSize: '100 g', sellUnit: 'pcs' },
  },
  {
    category: 'Spices & Condiments',
    name: 'Rock Salt (Sendha Namak) – 1kg',
    sku: 'GRC-RSALT-1K',
    barcode: '8901234560017',
    price: 38,
    costPrice: 22,
    taxCode: '2501',
    unit: 'kg',
    kind: 'physical',
    trackQty: true,
    qty: 90,
    meta: { packSize: '1 kg', sellUnit: 'kg' },
  },
  {
    category: 'Spices & Condiments',
    name: 'Iodised Salt – 1kg',
    sku: 'GRC-SALT-1K',
    barcode: '8901234560018',
    price: 22,
    costPrice: 12,
    taxCode: '2501',
    unit: 'kg',
    kind: 'physical',
    trackQty: true,
    qty: 200,
    brand: 'Tata Salt',
    meta: { packSize: '1 kg', sellUnit: 'kg' },
  },
  {
    category: 'Spices & Condiments',
    name: 'White Sugar – 1kg',
    sku: 'GRC-SUGAR-1K',
    barcode: '8901234560019',
    price: 48,
    costPrice: 36,
    taxCode: '1701',
    unit: 'kg',
    kind: 'physical',
    trackQty: true,
    qty: 180,
    meta: { packSize: '1 kg', sellUnit: 'kg' },
  },

  // ── Cooking Oil ───────────────────────────────────────────────────────────
  {
    category: 'Cooking Oil',
    name: 'Sunflower Oil – 1L',
    sku: 'GRC-SUNFL-1L',
    barcode: '8901234560020',
    price: 148,
    costPrice: 120,
    taxCode: '1512',
    unit: 'litre',
    kind: 'physical',
    trackQty: true,
    qty: 80,
    brand: 'Fortune',
    meta: { packSize: '1 L', sellUnit: 'litre' },
  },
  {
    category: 'Cooking Oil',
    name: 'Mustard Oil – 1L',
    sku: 'GRC-MUST-1L',
    barcode: '8901234560021',
    price: 168,
    costPrice: 135,
    taxCode: '1514',
    unit: 'litre',
    kind: 'physical',
    trackQty: true,
    qty: 60,
    brand: 'Emami',
    meta: { packSize: '1 L', sellUnit: 'litre' },
  },
  {
    category: 'Cooking Oil',
    name: 'Refined Groundnut Oil – 500ml',
    sku: 'GRC-GNUT-500ML',
    barcode: '8901234560022',
    price: 98,
    costPrice: 78,
    taxCode: '1508',
    unit: 'ml',
    kind: 'physical',
    trackQty: true,
    qty: 70,
    brand: 'Dhara',
    meta: { packSize: '500 ml', sellUnit: 'ml' },
  },

  // ── Dairy ─────────────────────────────────────────────────────────────────
  {
    category: 'Dairy',
    name: 'Full Cream Milk – 1L Pouch',
    sku: 'GRC-MILK-1L',
    barcode: '8901234560023',
    price: 64,
    costPrice: 52,
    taxCode: '0401',
    unit: 'litre',
    kind: 'physical',
    trackQty: true,
    qty: 120,
    brand: 'Amul',
    meta: { packSize: '1 L', expiryTracked: true, perishable: true, sellUnit: 'litre' },
  },
  {
    category: 'Dairy',
    name: 'Curd – 400g Cup',
    sku: 'GRC-CURD-400',
    barcode: '8901234560024',
    price: 38,
    costPrice: 28,
    taxCode: '0403',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 80,
    brand: 'Mother Dairy',
    meta: { packSize: '400 g', expiryTracked: true, perishable: true, sellUnit: 'pcs' },
  },
  {
    category: 'Dairy',
    name: 'Paneer – 200g Pack',
    sku: 'GRC-PANEER-200',
    barcode: '8901234560025',
    price: 95,
    costPrice: 72,
    taxCode: '0406',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 40,
    brand: 'Amul',
    meta: { packSize: '200 g', expiryTracked: true, perishable: true, sellUnit: 'pcs' },
  },
  {
    category: 'Dairy',
    name: 'Butter – 100g',
    sku: 'GRC-BUTTER-100',
    barcode: '8901234560026',
    price: 52,
    costPrice: 40,
    taxCode: '0405',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 60,
    brand: 'Amul',
    meta: { packSize: '100 g', expiryTracked: true, perishable: true, sellUnit: 'pcs' },
  },
  {
    category: 'Dairy',
    name: 'Cheese Slices – 200g (10 slices)',
    sku: 'GRC-CHEESE-200',
    barcode: '8901234560027',
    price: 120,
    costPrice: 90,
    taxCode: '0406',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 30,
    brand: 'Britannia',
    meta: { packSize: '200 g', slices: 10, expiryTracked: true, sellUnit: 'pcs' },
  },

  // ── Bakery ────────────────────────────────────────────────────────────────
  {
    category: 'Bakery',
    name: 'Whole Wheat Bread – 400g Loaf',
    sku: 'GRC-BREAD-WW',
    barcode: '8901234560028',
    price: 48,
    costPrice: 35,
    taxCode: '1905',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 60,
    brand: 'Britannia',
    meta: { packSize: '400 g', expiryTracked: true, perishable: true, sellUnit: 'pcs' },
  },
  {
    category: 'Bakery',
    name: 'Marie Biscuits – 250g',
    sku: 'GRC-MARIE-250',
    barcode: '8901234560029',
    price: 30,
    costPrice: 20,
    taxCode: '1905',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 150,
    brand: 'Britannia',
    meta: { packSize: '250 g', sellUnit: 'pcs' },
  },
  {
    category: 'Bakery',
    name: 'Glucose Biscuits – 250g',
    sku: 'GRC-GLUCO-250',
    barcode: '8901234560030',
    price: 25,
    costPrice: 16,
    taxCode: '1905',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 180,
    brand: 'Parle-G',
    meta: { packSize: '250 g', sellUnit: 'pcs' },
  },

  // ── Beverages ─────────────────────────────────────────────────────────────
  {
    category: 'Beverages',
    name: 'Mineral Water – 1L Bottle',
    sku: 'GRC-WTR-1L',
    barcode: '8901234560031',
    price: 20,
    costPrice: 12,
    taxCode: '2201',
    unit: 'bottle',
    kind: 'physical',
    trackQty: true,
    qty: 200,
    brand: 'Bisleri',
    meta: { packSize: '1 L', sellUnit: 'bottle' },
  },
  {
    category: 'Beverages',
    name: 'Packaged Drinking Water – 500ml',
    sku: 'GRC-WTR-500ML',
    barcode: '8901234560032',
    price: 12,
    costPrice: 7,
    taxCode: '2201',
    unit: 'bottle',
    kind: 'physical',
    trackQty: true,
    qty: 300,
    brand: 'Kinley',
    meta: { packSize: '500 ml', sellUnit: 'bottle' },
  },
  {
    category: 'Beverages',
    name: 'Cola – 600ml Bottle',
    sku: 'GRC-COLA-600',
    barcode: '8901234560033',
    price: 42,
    costPrice: 30,
    taxCode: '2202',
    unit: 'bottle',
    kind: 'physical',
    trackQty: true,
    qty: 100,
    brand: 'Coca-Cola',
    meta: { packSize: '600 ml', sellUnit: 'bottle' },
  },
  {
    category: 'Beverages',
    name: 'Orange Juice – 1L Carton',
    sku: 'GRC-OJ-1L',
    barcode: '8901234560034',
    price: 110,
    costPrice: 82,
    taxCode: '2009',
    unit: 'litre',
    kind: 'physical',
    trackQty: true,
    qty: 50,
    brand: 'Tropicana',
    meta: { packSize: '1 L', expiryTracked: true, sellUnit: 'litre' },
  },
  {
    category: 'Beverages',
    name: 'Tea Bags – 100 Count Box',
    sku: 'GRC-TEA-100BOX',
    barcode: '8901234560035',
    price: 180,
    costPrice: 130,
    taxCode: '0902',
    unit: 'box',
    kind: 'physical',
    trackQty: true,
    qty: 70,
    brand: 'Tata Tea',
    meta: { packSize: '100 count', sellUnit: 'box' },
  },
  {
    category: 'Beverages',
    name: 'Instant Coffee – 50g Jar',
    sku: 'GRC-COFFEE-50',
    barcode: '8901234560036',
    price: 195,
    costPrice: 148,
    taxCode: '0901',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 45,
    brand: 'Nescafé',
    meta: { packSize: '50 g', sellUnit: 'pcs' },
  },

  // ── Snacks ────────────────────────────────────────────────────────────────
  {
    category: 'Snacks',
    name: 'Namkeen Mix – 200g',
    sku: 'GRC-NMKN-200',
    barcode: '8901234560037',
    price: 58,
    costPrice: 40,
    taxCode: '2106',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 90,
    brand: 'Haldiram',
    meta: { packSize: '200 g', sellUnit: 'pcs' },
  },
  {
    category: 'Snacks',
    name: 'Potato Chips – Salted (80g)',
    sku: 'GRC-CHIPS-80',
    barcode: '8901234560038',
    price: 40,
    costPrice: 28,
    taxCode: '2005',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 120,
    brand: "Lay's",
    meta: { packSize: '80 g', sellUnit: 'pcs' },
  },
  {
    category: 'Snacks',
    name: 'Dark Chocolate Bar – 90g',
    sku: 'GRC-CHOC-90',
    barcode: '8901234560039',
    price: 95,
    costPrice: 70,
    taxCode: '1806',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 60,
    brand: 'Bournville',
    meta: { packSize: '90 g', sellUnit: 'pcs' },
  },

  // ── Fruits & Vegetables ───────────────────────────────────────────────────
  {
    category: 'Fruits & Vegetables',
    name: 'Tomatoes – Fresh (per kg)',
    sku: 'GRC-TOM-KG',
    barcode: '8901234560040',
    price: 35,
    costPrice: 20,
    taxCode: '0702',
    unit: 'kg',
    kind: 'physical',
    trackQty: true,
    qty: 50,
    meta: { sellUnit: 'kg', perishable: true },
  },
  {
    category: 'Fruits & Vegetables',
    name: 'Bananas – Dozen',
    sku: 'GRC-BANA-DOZ',
    barcode: '8901234560041',
    price: 50,
    costPrice: 30,
    taxCode: '0803',
    unit: 'dozen',
    kind: 'physical',
    trackQty: true,
    qty: 40,
    meta: { sellUnit: 'dozen', perishable: true },
  },
  {
    category: 'Fruits & Vegetables',
    name: 'Apples – per kg (Kashmiri)',
    sku: 'GRC-APPLE-KG',
    barcode: '8901234560042',
    price: 160,
    costPrice: 110,
    taxCode: '0808',
    unit: 'kg',
    kind: 'physical',
    trackQty: true,
    qty: 30,
    meta: { sellUnit: 'kg', perishable: true },
  },

  // ── Frozen Foods ─────────────────────────────────────────────────────────
  {
    category: 'Frozen Foods',
    name: 'Frozen Green Peas – 500g',
    sku: 'GRC-FPEAS-500',
    barcode: '8901234560043',
    price: 65,
    costPrice: 45,
    taxCode: '2004',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 40,
    brand: 'McCain',
    meta: { packSize: '500 g', frozen: true, expiryTracked: true, sellUnit: 'pcs' },
  },
  {
    category: 'Frozen Foods',
    name: 'Frozen French Fries – 400g',
    sku: 'GRC-FFRIES-400',
    barcode: '8901234560044',
    price: 120,
    costPrice: 85,
    taxCode: '2004',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 35,
    brand: 'McCain',
    meta: { packSize: '400 g', frozen: true, expiryTracked: true, sellUnit: 'pcs' },
  },

  // ── Cleaning Products ────────────────────────────────────────────────────
  {
    category: 'Cleaning Products',
    name: 'Dishwash Liquid – 500ml',
    sku: 'GRC-DISH-500',
    barcode: '8901234560045',
    price: 85,
    costPrice: 60,
    taxCode: '3402',
    unit: 'bottle',
    kind: 'physical',
    trackQty: true,
    qty: 80,
    brand: 'Vim',
    meta: { packSize: '500 ml', sellUnit: 'bottle' },
  },
  {
    category: 'Cleaning Products',
    name: 'Floor Cleaner – 1L',
    sku: 'GRC-FLOOR-1L',
    barcode: '8901234560046',
    price: 120,
    costPrice: 85,
    taxCode: '3808',
    unit: 'bottle',
    kind: 'physical',
    trackQty: true,
    qty: 60,
    brand: 'Lizol',
    meta: { packSize: '1 L', sellUnit: 'bottle' },
  },
  {
    category: 'Cleaning Products',
    name: 'Toilet Cleaner – 500ml',
    sku: 'GRC-TOILET-500',
    barcode: '8901234560047',
    price: 75,
    costPrice: 50,
    taxCode: '3402',
    unit: 'bottle',
    kind: 'physical',
    trackQty: true,
    qty: 50,
    brand: 'Harpic',
    meta: { packSize: '500 ml', sellUnit: 'bottle' },
  },

  // ── Personal Care ────────────────────────────────────────────────────────
  {
    category: 'Personal Care',
    name: 'Shampoo – Anti-Dandruff (340ml)',
    sku: 'GRC-SHAMP-340',
    barcode: '8901234560048',
    price: 195,
    costPrice: 145,
    taxCode: '3305',
    unit: 'bottle',
    kind: 'physical',
    trackQty: true,
    qty: 60,
    brand: 'Head & Shoulders',
    meta: { packSize: '340 ml', sellUnit: 'bottle' },
  },
  {
    category: 'Personal Care',
    name: 'Soap Bar – Sandalwood (100g × 4)',
    sku: 'GRC-SOAP-4PK',
    barcode: '8901234560049',
    price: 120,
    costPrice: 85,
    taxCode: '3401',
    unit: 'pack',
    kind: 'physical',
    trackQty: true,
    qty: 80,
    brand: 'Santoor',
    meta: { packSize: '4 × 100 g', sellUnit: 'pack' },
  },
  {
    category: 'Personal Care',
    name: 'Toothpaste – Whitening (150g)',
    sku: 'GRC-TOOTH-150',
    barcode: '8901234560050',
    price: 90,
    costPrice: 65,
    taxCode: '3306',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 100,
    brand: 'Colgate',
    meta: { packSize: '150 g', sellUnit: 'pcs' },
  },
];

export const GROCERY_CUSTOMERS = [
  { name: 'Sunita Verma', phone: '9702000001', email: 'sunita@grocery.demo', meta: {} },
  { name: 'Dinesh Patel', phone: '9702000002', email: 'dinesh@grocery.demo', meta: {} },
  { name: 'Lakshmi Bai', phone: '9702000003', email: 'lakshmi@grocery.demo', meta: {} },
  { name: 'Mahesh Shukla', phone: '9702000004', email: 'mahesh@grocery.demo', meta: {} },
  { name: 'Geeta Yadav', phone: '9702000005', email: 'geeta@grocery.demo', meta: {} },
  { name: 'Vinod Tiwari', phone: '9702000006', email: 'vinod@grocery.demo', meta: {} },
  { name: 'Sushma Kumari', phone: '9702000007', email: 'sushma@grocery.demo', meta: {} },
  { name: 'Ramesh Gupta', phone: '9702000008', email: 'ramesh@grocery.demo', meta: {} },
  { name: 'Asha Singh', phone: '9702000009', email: 'asha@grocery.demo', meta: {} },
  { name: 'Bhupesh Nair', phone: '9702000010', email: 'bhupesh@grocery.demo', meta: {} },
  { name: 'Champa Devi', phone: '9702000011', email: null, meta: {} },
  { name: 'Gopal Lal', phone: '9702000012', email: 'gopal@grocery.demo', meta: {} },
  { name: 'Hema Malini', phone: '9702000013', email: 'hema@grocery.demo', meta: {} },
  { name: 'Indira Bose', phone: '9702000014', email: null, meta: {} },
  { name: 'Jyoti Mishra', phone: '9702000015', email: 'jyoti@grocery.demo', meta: {} },
  { name: 'Krishnan Pillai', phone: '9702000016', email: 'krishnan@grocery.demo', meta: {} },
  { name: 'Lalita Sharma', phone: '9702000017', email: null, meta: {} },
  { name: 'Mohan Chand', phone: '9702000018', email: 'mohan@grocery.demo', meta: {} },
  { name: 'Nalini Patil', phone: '9702000019', email: 'nalini@grocery.demo', meta: {} },
  { name: 'Walk-in Customer', phone: '9702000020', email: null, meta: {} },
];

export const GROCERY_STAFF = [
  { email: 'grocery.manager@grocery.demo', fullName: 'Grocery Manager', role: 'manager', code: 'GR002' },
  { email: 'grocery.staff@grocery.demo', fullName: 'Grocery Cashier', role: 'cashier', code: 'GR003' },
];

export const GROCERY_SUPPLIERS = [
  { code: 'SUP-GRC-001', name: 'Agro Wholesale Hub', supplierType: 'wholesaler', contact: 'Suresh Shah', phone: '9900002001', email: 'supply@agrowholesale.demo', taxId: '24AGRWHUB01Z5', paymentTerm: 'net_30', dueDays: 30, creditLimit: 800000 },
  { code: 'SUP-GRC-002', name: 'FreshFarm Distributors', supplierType: 'distributor', contact: 'Anand Patil', phone: '9900002002', email: 'supply@freshfarm.demo', paymentTerm: 'net_7', dueDays: 7, creditLimit: 200000 },
  { code: 'SUP-GRC-003', name: 'Metro Dairy Supplies', supplierType: 'wholesaler', contact: 'Renu Bhatt', phone: '9900002003', email: 'supply@metrodairy.demo', paymentTerm: 'immediate', dueDays: 0, creditLimit: 300000 },
  { code: 'SUP-GRC-004', name: 'Packaged Goods Co', supplierType: 'distributor', contact: 'Dilip Roy', phone: '9900002004', email: 'supply@pkggoods.demo', paymentTerm: 'net_15', dueDays: 15, creditLimit: 500000 },
  { code: 'SUP-GRC-005', name: 'Spice Route Traders', supplierType: 'wholesaler', contact: 'Vijay Menon', phone: '9900002005', email: 'supply@spiceroute.demo', paymentTerm: 'net_30', dueDays: 30, creditLimit: 250000 },
  { code: 'SUP-GRC-006', name: 'Cold Chain Express', supplierType: 'services', contact: 'Lakshmi Rao', phone: '9900002006', email: 'supply@coldchain.demo', paymentTerm: 'net_15', dueDays: 15, creditLimit: 150000 },
  { code: 'SUP-GRC-007', name: 'Beverage Distributors India', supplierType: 'distributor', contact: 'Prem Kumar', phone: '9900002007', email: 'supply@bevdist.demo', paymentTerm: 'net_30', dueDays: 30, creditLimit: 400000 },
  { code: 'SUP-GRC-008', name: 'Personal Care Direct', supplierType: 'wholesaler', contact: 'Meena Kapoor', phone: '9900002008', email: 'supply@pcdirect.demo', paymentTerm: 'net_30', dueDays: 30, creditLimit: 200000 },
];
