/**
 * Gym / Fitness Center — 50 realistic products & services.
 * No business-type if/else — pure structured data.
 * All items belong to the tenant that imports this catalog.
 */

export type CatalogItem = {
  category: string;
  name: string;
  sku: string;
  price: number;
  costPrice: number;
  taxCode: string;
  unit: string;
  kind: 'physical' | 'service';
  trackQty: boolean;
  qty: number;
  brand?: string;
  description?: string;
  meta?: Record<string, unknown>;
};

export const GYM_CATEGORIES = [
  'Membership Plans',
  'Personal Training',
  'Group Classes',
  'Fitness Assessment',
  'Nutrition',
  'Merchandise',
  'Supplements',
  'Accessories',
];

export const GYM_PRODUCTS: CatalogItem[] = [
  // ── Membership Plans ──────────────────────────────────────────────────────
  {
    category: 'Membership Plans',
    name: 'Monthly Membership – Standard',
    sku: 'GYM-MEM-STD-1M',
    price: 1500,
    costPrice: 300,
    taxCode: '9997',
    unit: 'month',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Full gym access — 30 days',
    meta: { durationDays: 30, membershipTier: 'standard', autoRenew: true },
  },
  {
    category: 'Membership Plans',
    name: 'Monthly Membership – Premium',
    sku: 'GYM-MEM-PRM-1M',
    price: 2500,
    costPrice: 500,
    taxCode: '9997',
    unit: 'month',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Full gym + sauna + locker — 30 days',
    meta: { durationDays: 30, membershipTier: 'premium', autoRenew: true },
  },
  {
    category: 'Membership Plans',
    name: 'Quarterly Membership – Standard',
    sku: 'GYM-MEM-STD-3M',
    price: 4000,
    costPrice: 800,
    taxCode: '9997',
    unit: 'quarter',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Full gym access — 90 days',
    meta: { durationDays: 90, membershipTier: 'standard', autoRenew: true },
  },
  {
    category: 'Membership Plans',
    name: 'Quarterly Membership – Premium',
    sku: 'GYM-MEM-PRM-3M',
    price: 6500,
    costPrice: 1300,
    taxCode: '9997',
    unit: 'quarter',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Full gym + sauna + locker — 90 days',
    meta: { durationDays: 90, membershipTier: 'premium', autoRenew: true },
  },
  {
    category: 'Membership Plans',
    name: 'Half-Year Membership',
    sku: 'GYM-MEM-6M',
    price: 7500,
    costPrice: 1500,
    taxCode: '9997',
    unit: 'period',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Full gym access — 180 days',
    meta: { durationDays: 180, membershipTier: 'standard' },
  },
  {
    category: 'Membership Plans',
    name: 'Annual Membership – Standard',
    sku: 'GYM-MEM-STD-1Y',
    price: 13000,
    costPrice: 2600,
    taxCode: '9997',
    unit: 'year',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Full gym access — 365 days',
    meta: { durationDays: 365, membershipTier: 'standard', autoRenew: true },
  },
  {
    category: 'Membership Plans',
    name: 'Annual Membership – Gold',
    sku: 'GYM-MEM-GLD-1Y',
    price: 20000,
    costPrice: 4000,
    taxCode: '9997',
    unit: 'year',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Unlimited access, towel service, priority booking — 365 days',
    meta: { durationDays: 365, membershipTier: 'gold', autoRenew: true },
  },
  {
    category: 'Membership Plans',
    name: 'Student Monthly Membership',
    sku: 'GYM-MEM-STU-1M',
    price: 999,
    costPrice: 200,
    taxCode: '9997',
    unit: 'month',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Valid student ID required — 30 days',
    meta: { durationDays: 30, membershipTier: 'student' },
  },
  {
    category: 'Membership Plans',
    name: 'Couple Monthly Membership',
    sku: 'GYM-MEM-CPL-1M',
    price: 2500,
    costPrice: 500,
    taxCode: '9997',
    unit: 'month',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: '2 members — 30 days',
    meta: { durationDays: 30, membershipTier: 'couple', seats: 2 },
  },
  {
    category: 'Membership Plans',
    name: 'Day Pass',
    sku: 'GYM-DAYPASS',
    price: 300,
    costPrice: 60,
    taxCode: '9997',
    unit: 'day',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Single-day gym access',
    meta: { durationDays: 1 },
  },

  // ── Personal Training ────────────────────────────────────────────────────
  {
    category: 'Personal Training',
    name: 'PT Session – 1 Hour (Single)',
    sku: 'GYM-PT-1HR',
    price: 1200,
    costPrice: 600,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'One-on-one personal training session',
    meta: { durationMinutes: 60, staffSkill: 'Personal Trainer' },
  },
  {
    category: 'Personal Training',
    name: 'PT Package – 10 Sessions',
    sku: 'GYM-PT-10S',
    price: 10000,
    costPrice: 5000,
    taxCode: '9997',
    unit: 'package',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: '10 one-hour PT sessions (valid 90 days)',
    meta: { sessions: 10, validDays: 90, staffSkill: 'Personal Trainer' },
  },
  {
    category: 'Personal Training',
    name: 'PT Package – 20 Sessions',
    sku: 'GYM-PT-20S',
    price: 18000,
    costPrice: 9000,
    taxCode: '9997',
    unit: 'package',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: '20 one-hour PT sessions (valid 180 days)',
    meta: { sessions: 20, validDays: 180, staffSkill: 'Personal Trainer' },
  },
  {
    category: 'Personal Training',
    name: 'Body Transformation Program – 3 Months',
    sku: 'GYM-BTP-3M',
    price: 25000,
    costPrice: 12500,
    taxCode: '9997',
    unit: 'package',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Personalised 3-month transformation with daily tracking',
    meta: { durationDays: 90, staffSkill: 'Senior Trainer' },
  },

  // ── Group Classes ─────────────────────────────────────────────────────────
  {
    category: 'Group Classes',
    name: 'Yoga – Monthly Pass',
    sku: 'GYM-YOG-1M',
    price: 1800,
    costPrice: 360,
    taxCode: '9997',
    unit: 'month',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Unlimited yoga classes for 30 days',
    meta: { durationDays: 30, classType: 'yoga', maxPerClass: 15 },
  },
  {
    category: 'Group Classes',
    name: 'Zumba – Monthly Pass',
    sku: 'GYM-ZUM-1M',
    price: 1500,
    costPrice: 300,
    taxCode: '9997',
    unit: 'month',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Unlimited Zumba classes for 30 days',
    meta: { durationDays: 30, classType: 'zumba' },
  },
  {
    category: 'Group Classes',
    name: 'CrossFit – Monthly Pass',
    sku: 'GYM-CFT-1M',
    price: 2800,
    costPrice: 560,
    taxCode: '9997',
    unit: 'month',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'WOD + open gym — 30 days',
    meta: { durationDays: 30, classType: 'crossfit' },
  },
  {
    category: 'Group Classes',
    name: 'Strength Training – Group (Monthly)',
    sku: 'GYM-STR-1M',
    price: 2200,
    costPrice: 440,
    taxCode: '9997',
    unit: 'month',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Group strength & conditioning — 30 days',
    meta: { durationDays: 30, classType: 'strength' },
  },
  {
    category: 'Group Classes',
    name: 'Cardio HIIT – Monthly Pass',
    sku: 'GYM-HIIT-1M',
    price: 1600,
    costPrice: 320,
    taxCode: '9997',
    unit: 'month',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'High-intensity interval training — 30 days',
    meta: { durationDays: 30, classType: 'hiit' },
  },
  {
    category: 'Group Classes',
    name: 'Yoga – Single Session Drop-In',
    sku: 'GYM-YOG-1S',
    price: 400,
    costPrice: 80,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Walk-in yoga class',
    meta: { durationMinutes: 60, classType: 'yoga' },
  },
  {
    category: 'Group Classes',
    name: 'Pilates – Monthly Pass',
    sku: 'GYM-PIL-1M',
    price: 2000,
    costPrice: 400,
    taxCode: '9997',
    unit: 'month',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Pilates mat and reformer classes — 30 days',
    meta: { durationDays: 30, classType: 'pilates' },
  },
  {
    category: 'Group Classes',
    name: 'Aerobics – Monthly Pass',
    sku: 'GYM-AER-1M',
    price: 1200,
    costPrice: 240,
    taxCode: '9997',
    unit: 'month',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Step aerobics and floor classes — 30 days',
    meta: { durationDays: 30, classType: 'aerobics' },
  },

  // ── Fitness Assessment ────────────────────────────────────────────────────
  {
    category: 'Fitness Assessment',
    name: 'Body Composition Analysis',
    sku: 'GYM-BCA-01',
    price: 500,
    costPrice: 100,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'InBody / BIA body composition scan and report',
    meta: { durationMinutes: 30 },
  },
  {
    category: 'Fitness Assessment',
    name: 'Fitness Goal Consultation',
    sku: 'GYM-FGC-01',
    price: 0,
    costPrice: 0,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Complimentary goal-setting session with a trainer',
    meta: { durationMinutes: 45 },
  },
  {
    category: 'Fitness Assessment',
    name: 'VO2 Max Fitness Test',
    sku: 'GYM-VO2-01',
    price: 800,
    costPrice: 200,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Cardiorespiratory fitness assessment',
    meta: { durationMinutes: 60 },
  },

  // ── Nutrition ─────────────────────────────────────────────────────────────
  {
    category: 'Nutrition',
    name: 'Nutrition Consultation – Single',
    sku: 'GYM-NUT-1S',
    price: 1000,
    costPrice: 500,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'One-on-one diet planning with a nutritionist',
    meta: { durationMinutes: 60, staffSkill: 'Nutritionist' },
  },
  {
    category: 'Nutrition',
    name: 'Diet Plan – 3-Month Program',
    sku: 'GYM-NUT-3M',
    price: 3500,
    costPrice: 1750,
    taxCode: '9997',
    unit: 'package',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Personalised 3-month diet plan with bi-weekly reviews',
    meta: { durationDays: 90, staffSkill: 'Nutritionist' },
  },

  // ── Merchandise ───────────────────────────────────────────────────────────
  {
    category: 'Merchandise',
    name: 'Gym T-Shirt – Dri-Fit (M)',
    sku: 'GYM-TSHIRT-M',
    price: 699,
    costPrice: 280,
    taxCode: '6109',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 50,
    brand: 'FitWear',
    description: 'Moisture-wicking performance tee — Medium',
    meta: { size: 'M', color: 'Black' },
  },
  {
    category: 'Merchandise',
    name: 'Gym T-Shirt – Dri-Fit (L)',
    sku: 'GYM-TSHIRT-L',
    price: 699,
    costPrice: 280,
    taxCode: '6109',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 40,
    brand: 'FitWear',
    description: 'Moisture-wicking performance tee — Large',
    meta: { size: 'L', color: 'Black' },
  },
  {
    category: 'Merchandise',
    name: 'Gym Track Pants',
    sku: 'GYM-PANTS-M',
    price: 999,
    costPrice: 400,
    taxCode: '6211',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 30,
    brand: 'FitWear',
    description: 'Quick-dry training track pants — Medium',
    meta: { size: 'M', color: 'Grey' },
  },
  {
    category: 'Merchandise',
    name: 'Gym Water Bottle – 1L Sipper',
    sku: 'GYM-BTL-1L',
    price: 399,
    costPrice: 150,
    taxCode: '3923',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 60,
    brand: 'HydroFit',
    description: 'BPA-free 1L stainless sipper with time marker',
    meta: { capacity: '1L', material: 'stainless' },
  },
  {
    category: 'Merchandise',
    name: 'Microfibre Gym Towel',
    sku: 'GYM-TOWEL-01',
    price: 299,
    costPrice: 100,
    taxCode: '6302',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 80,
    brand: 'FitWear',
    description: 'Quick-dry gym towel — 50×100cm',
  },
  {
    category: 'Merchandise',
    name: 'Gym Gloves – Medium',
    sku: 'GYM-GLOVES-M',
    price: 599,
    costPrice: 220,
    taxCode: '6216',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 35,
    brand: 'IronGrip',
    description: 'Anti-slip padded gym gloves — Medium',
    meta: { size: 'M' },
  },
  {
    category: 'Merchandise',
    name: 'Resistance Band Set (5-pack)',
    sku: 'GYM-RES-5PK',
    price: 799,
    costPrice: 300,
    taxCode: '3926',
    unit: 'set',
    kind: 'physical',
    trackQty: true,
    qty: 25,
    brand: 'BandFlex',
    description: '5 resistance levels — light to extra heavy',
  },
  {
    category: 'Merchandise',
    name: 'Yoga Mat – 6mm Non-Slip',
    sku: 'GYM-YOGAMAT-01',
    price: 1199,
    costPrice: 500,
    taxCode: '9506',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 20,
    brand: 'ZenFlex',
    description: '6mm TPE non-slip yoga mat with carry strap',
  },
  {
    category: 'Merchandise',
    name: 'Gym Bag – 30L',
    sku: 'GYM-BAG-30L',
    price: 1499,
    costPrice: 600,
    taxCode: '4202',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 20,
    brand: 'FitWear',
    description: 'Durable gym duffel with shoe compartment',
  },
  {
    category: 'Merchandise',
    name: 'Skipping Rope – Speed',
    sku: 'GYM-SKIPROPE-01',
    price: 349,
    costPrice: 120,
    taxCode: '9506',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 40,
    brand: 'SpeedJump',
    description: 'Adjustable steel cable speed rope',
  },

  // ── Supplements ───────────────────────────────────────────────────────────
  {
    category: 'Supplements',
    name: 'Whey Protein – Chocolate (1kg)',
    sku: 'GYM-WHEY-CHO-1K',
    price: 2499,
    costPrice: 1200,
    taxCode: '2106',
    unit: 'kg',
    kind: 'physical',
    trackQty: true,
    qty: 30,
    brand: 'MuscleFuel',
    description: '24g protein per serving — Chocolate flavour',
    meta: { flavour: 'Chocolate', servings: 33 },
  },
  {
    category: 'Supplements',
    name: 'Whey Protein – Vanilla (1kg)',
    sku: 'GYM-WHEY-VAN-1K',
    price: 2499,
    costPrice: 1200,
    taxCode: '2106',
    unit: 'kg',
    kind: 'physical',
    trackQty: true,
    qty: 20,
    brand: 'MuscleFuel',
    description: '24g protein per serving — Vanilla flavour',
    meta: { flavour: 'Vanilla', servings: 33 },
  },
  {
    category: 'Supplements',
    name: 'Creatine Monohydrate – 300g',
    sku: 'GYM-CREAT-300',
    price: 899,
    costPrice: 400,
    taxCode: '2106',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 25,
    brand: 'MuscleFuel',
    description: 'Micronised creatine — 60 servings',
    meta: { servings: 60, grams: 300 },
  },
  {
    category: 'Supplements',
    name: 'BCAA – Watermelon (300g)',
    sku: 'GYM-BCAA-WM-300',
    price: 1299,
    costPrice: 600,
    taxCode: '2106',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 18,
    brand: 'MuscleFuel',
    description: '2:1:1 BCAA — 30 servings Watermelon',
    meta: { flavour: 'Watermelon', servings: 30 },
  },
  {
    category: 'Supplements',
    name: 'Mass Gainer – Chocolate (3kg)',
    sku: 'GYM-MASS-CHO-3K',
    price: 3499,
    costPrice: 1700,
    taxCode: '2106',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 12,
    brand: 'BulkPower',
    description: '1250 cal per serving — for hard gainers',
    meta: { flavour: 'Chocolate', servings: 20 },
  },
  {
    category: 'Supplements',
    name: 'Pre-Workout – Explosive (240g)',
    sku: 'GYM-PRE-EXP-240',
    price: 1599,
    costPrice: 750,
    taxCode: '2106',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 20,
    brand: 'BlastFuel',
    description: 'Caffeine + Beta-Alanine + Citrulline — 30 servings',
    meta: { servings: 30, caffeinePerServing: 200 },
  },
  {
    category: 'Supplements',
    name: 'Multivitamin – 60 Tablets',
    sku: 'GYM-MULTIVIT-60',
    price: 599,
    costPrice: 250,
    taxCode: '3004',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 40,
    brand: 'VitaActive',
    description: 'Complete daily multivitamin for athletes',
    meta: { tablets: 60 },
  },

  // ── Accessories ───────────────────────────────────────────────────────────
  {
    category: 'Accessories',
    name: 'Foam Roller – Deep Tissue',
    sku: 'GYM-FOAM-01',
    price: 999,
    costPrice: 400,
    taxCode: '9506',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 15,
    brand: 'RecoverFlex',
    description: '33cm EVA foam roller for myofascial release',
  },
  {
    category: 'Accessories',
    name: 'Wrist Wraps – Pair',
    sku: 'GYM-WRISTRAP-PR',
    price: 499,
    costPrice: 180,
    taxCode: '6217',
    unit: 'pair',
    kind: 'physical',
    trackQty: true,
    qty: 30,
    brand: 'IronGrip',
    description: 'Adjustable wrist support straps',
  },
  {
    category: 'Accessories',
    name: 'Knee Sleeves – Pair (M)',
    sku: 'GYM-KNEE-M-PR',
    price: 799,
    costPrice: 300,
    taxCode: '6307',
    unit: 'pair',
    kind: 'physical',
    trackQty: true,
    qty: 20,
    brand: 'IronGrip',
    description: '5mm neoprene knee sleeves — Medium',
    meta: { size: 'M' },
  },
  {
    category: 'Accessories',
    name: 'AB Wheel Roller',
    sku: 'GYM-ABWHEEL-01',
    price: 449,
    costPrice: 170,
    taxCode: '9506',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 25,
    brand: 'CoreFlex',
    description: 'Double-wheel ab roller with non-slip grips',
  },
  {
    category: 'Accessories',
    name: 'Gym Lock – Combination',
    sku: 'GYM-LOCK-01',
    price: 199,
    costPrice: 70,
    taxCode: '8301',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 50,
    brand: 'SecureFit',
    description: '4-digit combination locker padlock',
  },
  {
    category: 'Accessories',
    name: 'Shaker Bottle – 700ml',
    sku: 'GYM-SHAKER-700',
    price: 249,
    costPrice: 90,
    taxCode: '3923',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 60,
    brand: 'MixPro',
    description: 'BPA-free protein shaker with mixing ball',
    meta: { capacity: '700ml' },
  },
  {
    category: 'Accessories',
    name: 'Chalk Block – Gym Grade',
    sku: 'GYM-CHALK-01',
    price: 149,
    costPrice: 50,
    taxCode: '3816',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 40,
    brand: 'IronGrip',
    description: 'Magnesium carbonate chalk block for grip',
  },
  {
    category: 'Accessories',
    name: 'Heart Rate Monitor Band',
    sku: 'GYM-HRM-01',
    price: 1999,
    costPrice: 900,
    taxCode: '9018',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 10,
    brand: 'PulseFit',
    description: 'Chest strap heart rate monitor — Bluetooth',
  },
];

/** Customers for gym demo */
export const GYM_CUSTOMERS = [
  { name: 'Arjun Sharma', phone: '9701000001', email: 'arjun@gym.demo', meta: { fitnessGoal: 'Weight loss' } },
  { name: 'Divya Nair', phone: '9701000002', email: 'divya@gym.demo', meta: { fitnessGoal: 'Muscle gain' } },
  { name: 'Kabir Singh', phone: '9701000003', email: 'kabir@gym.demo', meta: { fitnessGoal: 'Endurance' } },
  { name: 'Meera Joshi', phone: '9701000004', email: 'meera@gym.demo', meta: { fitnessGoal: 'Flexibility' } },
  { name: 'Ravi Kumar', phone: '9701000005', email: 'ravi@gym.demo', meta: { fitnessGoal: 'Weight loss' } },
  { name: 'Sneha Iyer', phone: '9701000006', email: 'sneha@gym.demo', meta: { fitnessGoal: 'Strength' } },
  { name: 'Tanmay Bhat', phone: '9701000007', email: 'tanmay@gym.demo', meta: { fitnessGoal: 'Muscle gain' } },
  { name: 'Priya Gupta', phone: '9701000008', email: 'priya.g@gym.demo', meta: { fitnessGoal: 'Toning' } },
  { name: 'Ankur Mishra', phone: '9701000009', email: 'ankur@gym.demo', meta: {} },
  { name: 'Kavita Rao', phone: '9701000010', email: 'kavita@gym.demo', meta: { fitnessGoal: 'Yoga' } },
  { name: 'Sameer Desai', phone: '9701000011', email: 'sameer@gym.demo', meta: { fitnessGoal: 'CrossFit' } },
  { name: 'Ritika Sahu', phone: '9701000012', email: 'ritika@gym.demo', meta: { fitnessGoal: 'Weight loss' } },
  { name: 'Yash Mehta', phone: '9701000013', email: 'yash@gym.demo', meta: { fitnessGoal: 'Bodybuilding' } },
  { name: 'Ananya Pillai', phone: '9701000014', email: 'ananya@gym.demo', meta: { fitnessGoal: 'Dance fitness' } },
  { name: 'Rohit Verma', phone: '9701000015', email: 'rohit@gym.demo', meta: { fitnessGoal: 'Cardio' } },
  { name: 'Deepa Krishna', phone: '9701000016', email: 'deepa@gym.demo', meta: { fitnessGoal: 'Pilates' } },
  { name: 'Nitin Agarwal', phone: '9701000017', email: 'nitin@gym.demo', meta: {} },
  { name: 'Pooja Saxena', phone: '9701000018', email: 'pooja@gym.demo', meta: { fitnessGoal: 'HIIT' } },
  { name: 'Karthik Reddy', phone: '9701000019', email: 'karthik@gym.demo', meta: { fitnessGoal: 'Strength' } },
  { name: 'Walk-in Guest', phone: '9701000020', email: null, meta: {} },
];

/** Staff / users for gym */
export const GYM_STAFF = [
  { email: 'gym.manager@gym.demo', fullName: 'Gym Manager', role: 'manager', code: 'GM002' },
  { email: 'gym.staff@gym.demo', fullName: 'Gym Staff', role: 'cashier', code: 'GM003' },
];

/** Suppliers for gym */
export const GYM_SUPPLIERS = [
  {
    code: 'SUP-GYM-001', name: 'MuscleFuel Distributors', supplierType: 'wholesaler',
    contact: 'Rajesh Kapur', phone: '9900001001', email: 'supply@musclefuel.demo',
    taxId: '29MUSCLEFUEL1Z5', paymentTerm: 'net_30', dueDays: 30, creditLimit: 500000,
  },
  {
    code: 'SUP-GYM-002', name: 'FitGear Wholesale', supplierType: 'wholesaler',
    contact: 'Anita Bhatt', phone: '9900001002', email: 'supply@fitgear.demo',
    taxId: '29FITGEARWH01Z5', paymentTerm: 'net_15', dueDays: 15, creditLimit: 200000,
  },
  {
    code: 'SUP-GYM-003', name: 'ProEquipment Ltd', supplierType: 'manufacturer',
    contact: 'Sunil Mehta', phone: '9900001003', email: 'supply@proequip.demo',
    paymentTerm: 'net_30', dueDays: 30, creditLimit: 300000,
  },
  {
    code: 'SUP-GYM-004', name: 'BulkSupp India', supplierType: 'wholesaler',
    contact: 'Nidhi Sharma', phone: '9900001004', email: 'supply@bulksupp.demo',
    paymentTerm: 'immediate', dueDays: 0, creditLimit: 100000,
  },
  {
    code: 'SUP-GYM-005', name: 'Gym Apparel Co', supplierType: 'manufacturer',
    contact: 'Vivek Rao', phone: '9900001005', email: 'supply@gymapparel.demo',
    paymentTerm: 'net_30', dueDays: 30, creditLimit: 150000,
  },
];
