/**
 * Salon — 50 realistic services + retail products.
 * Business type: salon (service + sale commerce modes).
 * Pure structured data — no business-type conditionals.
 */

export type CatalogItem = {
  category: string;
  name: string;
  sku: string;
  price: number;
  costPrice: number;
  taxCode: string;
  unit: string;
  kind: 'physical' | 'service';
  trackQty: boolean;
  qty: number;
  brand?: string;
  description?: string;
  meta?: Record<string, unknown>;
};

export const SALON_CATEGORIES = [
  'Hair Services',
  'Skin & Facial',
  'Nail Care',
  'Body Treatments',
  'Bridal & Packages',
  'Threading & Waxing',
  'Beard & Men Grooming',
  'Hair Products',
  'Skin Products',
  'Accessories',
];

export const SALON_PRODUCTS: CatalogItem[] = [
  // ── Hair Services ─────────────────────────────────────────────────────────
  {
    category: 'Hair Services',
    name: 'Haircut – Men (Basic)',
    sku: 'SAL-CUT-MEN-BSC',
    price: 350,
    costPrice: 70,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Wash + cut + basic styling',
    meta: { durationMinutes: 30, staffSkill: 'Barber' },
  },
  {
    category: 'Hair Services',
    name: 'Haircut – Men (Premium)',
    sku: 'SAL-CUT-MEN-PRM',
    price: 600,
    costPrice: 120,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Wash + cut + styling + head massage',
    meta: { durationMinutes: 45, staffSkill: 'Senior Stylist' },
  },
  {
    category: 'Hair Services',
    name: 'Haircut – Women (Short)',
    sku: 'SAL-CUT-WMN-SH',
    price: 650,
    costPrice: 130,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Shampoo + short hair cut + blow-dry',
    meta: { durationMinutes: 45, staffSkill: 'Stylist', hairLength: 'short' },
  },
  {
    category: 'Hair Services',
    name: 'Haircut – Women (Long)',
    sku: 'SAL-CUT-WMN-LG',
    price: 900,
    costPrice: 180,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Shampoo + long hair cut + blow-dry',
    meta: { durationMinutes: 60, staffSkill: 'Stylist', hairLength: 'long' },
  },
  {
    category: 'Hair Services',
    name: 'Hair Wash & Blow Dry',
    sku: 'SAL-WSHBLW-01',
    price: 450,
    costPrice: 90,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Professional shampoo + condition + blow-dry',
    meta: { durationMinutes: 40, staffSkill: 'Stylist' },
  },
  {
    category: 'Hair Services',
    name: 'Hair Colour – Global (Short)',
    sku: 'SAL-COLOR-GLB-SH',
    price: 1500,
    costPrice: 600,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Full head colour — short hair (up to shoulder)',
    meta: { durationMinutes: 90, staffSkill: 'Colour Specialist', hairLength: 'short' },
  },
  {
    category: 'Hair Services',
    name: 'Hair Colour – Global (Long)',
    sku: 'SAL-COLOR-GLB-LG',
    price: 2500,
    costPrice: 1000,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Full head colour — long hair (below shoulder)',
    meta: { durationMinutes: 120, staffSkill: 'Colour Specialist', hairLength: 'long' },
  },
  {
    category: 'Hair Services',
    name: 'Highlights / Balayage',
    sku: 'SAL-HILITE-01',
    price: 3500,
    costPrice: 1400,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Partial or full balayage with toning',
    meta: { durationMinutes: 150, staffSkill: 'Colour Specialist' },
  },
  {
    category: 'Hair Services',
    name: 'Hair Spa – Keratin Treatment',
    sku: 'SAL-SPA-KER',
    price: 3000,
    costPrice: 900,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Keratin smoothing treatment — 3-month results',
    meta: { durationMinutes: 120, staffSkill: 'Senior Stylist' },
  },
  {
    category: 'Hair Services',
    name: 'Hair Spa – Deep Conditioning',
    sku: 'SAL-SPA-DEEP',
    price: 1200,
    costPrice: 400,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Mask + steam + deep conditioning',
    meta: { durationMinutes: 60, staffSkill: 'Stylist' },
  },
  {
    category: 'Hair Services',
    name: 'Hair Straightening – Permanent',
    sku: 'SAL-STRT-PERM',
    price: 5000,
    costPrice: 1800,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Permanent hair straightening treatment',
    meta: { durationMinutes: 180, staffSkill: 'Senior Stylist' },
  },
  {
    category: 'Hair Services',
    name: 'Hair Rebonding',
    sku: 'SAL-REBN-01',
    price: 4500,
    costPrice: 1600,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Full hair rebonding with protein treatment',
    meta: { durationMinutes: 180, staffSkill: 'Senior Stylist' },
  },
  {
    category: 'Hair Services',
    name: 'Kids Haircut (Under 10)',
    sku: 'SAL-CUT-KIDS',
    price: 250,
    costPrice: 50,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Gentle kids haircut with styling',
    meta: { durationMinutes: 20, ageGroup: 'under_10' },
  },

  // ── Skin & Facial ─────────────────────────────────────────────────────────
  {
    category: 'Skin & Facial',
    name: 'Basic Cleanup',
    sku: 'SAL-CLUP-BSC',
    price: 600,
    costPrice: 180,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Cleansing + scrub + mask + toner',
    meta: { durationMinutes: 45, staffSkill: 'Beautician' },
  },
  {
    category: 'Skin & Facial',
    name: 'D-Tan Facial',
    sku: 'SAL-DTAN-01',
    price: 900,
    costPrice: 270,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Tan removal + brightening facial',
    meta: { durationMinutes: 60, staffSkill: 'Beautician' },
  },
  {
    category: 'Skin & Facial',
    name: 'Anti-Ageing Facial',
    sku: 'SAL-ANTIA-01',
    price: 1800,
    costPrice: 540,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Premium anti-ageing treatment with collagen mask',
    meta: { durationMinutes: 75, staffSkill: 'Senior Beautician' },
  },
  {
    category: 'Skin & Facial',
    name: 'Gold Facial',
    sku: 'SAL-GOLD-01',
    price: 2500,
    costPrice: 750,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Luxury gold leaf facial with massage',
    meta: { durationMinutes: 90, staffSkill: 'Senior Beautician' },
  },
  {
    category: 'Skin & Facial',
    name: 'Oxygeo Facial',
    sku: 'SAL-OXY-01',
    price: 3500,
    costPrice: 1200,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'OxyGeneo® 3-in-1 facial — exfoliation + infusion + oxygenation',
    meta: { durationMinutes: 90, staffSkill: 'Senior Beautician' },
  },

  // ── Nail Care ─────────────────────────────────────────────────────────────
  {
    category: 'Nail Care',
    name: 'Basic Manicure',
    sku: 'SAL-MANIC-BSC',
    price: 450,
    costPrice: 135,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Soak + file + cuticle care + polish',
    meta: { durationMinutes: 30, staffSkill: 'Nail Tech' },
  },
  {
    category: 'Nail Care',
    name: 'Gel Manicure',
    sku: 'SAL-MANIC-GEL',
    price: 900,
    costPrice: 270,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Long-lasting gel polish manicure — 2-week wear',
    meta: { durationMinutes: 50, staffSkill: 'Nail Tech' },
  },
  {
    category: 'Nail Care',
    name: 'Basic Pedicure',
    sku: 'SAL-PEDIC-BSC',
    price: 600,
    costPrice: 180,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Soak + scrub + foot massage + polish',
    meta: { durationMinutes: 45, staffSkill: 'Nail Tech' },
  },
  {
    category: 'Nail Care',
    name: 'Luxury Pedicure',
    sku: 'SAL-PEDIC-LUX',
    price: 1200,
    costPrice: 360,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Extended pedicure with paraffin wax and scrub',
    meta: { durationMinutes: 75, staffSkill: 'Senior Nail Tech' },
  },
  {
    category: 'Nail Care',
    name: 'Nail Art – Per Nail',
    sku: 'SAL-NAILART-01',
    price: 100,
    costPrice: 30,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Custom nail art design — price per nail',
    meta: { durationMinutes: 5, staffSkill: 'Nail Artist' },
  },

  // ── Body Treatments ───────────────────────────────────────────────────────
  {
    category: 'Body Treatments',
    name: 'Swedish Full Body Massage – 60 Min',
    sku: 'SAL-MASS-60',
    price: 2000,
    costPrice: 800,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Relaxation full body massage with essential oils',
    meta: { durationMinutes: 60, staffSkill: 'Massage Therapist' },
  },
  {
    category: 'Body Treatments',
    name: 'Head Massage – 20 Min',
    sku: 'SAL-HEADMASS-20',
    price: 400,
    costPrice: 160,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Champi head and scalp massage',
    meta: { durationMinutes: 20, staffSkill: 'Stylist' },
  },
  {
    category: 'Body Treatments',
    name: 'Back & Shoulder Massage – 30 Min',
    sku: 'SAL-BACKMASS-30',
    price: 900,
    costPrice: 360,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Targeted back and shoulder relief massage',
    meta: { durationMinutes: 30, staffSkill: 'Massage Therapist' },
  },

  // ── Bridal & Packages ─────────────────────────────────────────────────────
  {
    category: 'Bridal & Packages',
    name: 'Bridal Package – Full Day',
    sku: 'SAL-BRID-FD',
    price: 20000,
    costPrice: 8000,
    taxCode: '9997',
    unit: 'package',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Bridal makeup + hair + draping + mehndi coordination',
    meta: { durationMinutes: 300, staffSkill: 'Senior Artist' },
  },
  {
    category: 'Bridal & Packages',
    name: 'Groom Package',
    sku: 'SAL-GROOM-PKG',
    price: 5000,
    costPrice: 2000,
    taxCode: '9997',
    unit: 'package',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Groom grooming — haircut + facial + beard + manicure',
    meta: { durationMinutes: 120, staffSkill: 'Senior Stylist' },
  },
  {
    category: 'Bridal & Packages',
    name: 'Pre-Bridal Package – 3 Sessions',
    sku: 'SAL-PREBIRD-3S',
    price: 12000,
    costPrice: 4800,
    taxCode: '9997',
    unit: 'package',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: '3 sessions of skin treatment + waxing + facial',
    meta: { sessions: 3, validDays: 30 },
  },

  // ── Threading & Waxing ────────────────────────────────────────────────────
  {
    category: 'Threading & Waxing',
    name: 'Eyebrow Threading',
    sku: 'SAL-THRD-BROW',
    price: 80,
    costPrice: 16,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Precise eyebrow shaping by threading',
    meta: { durationMinutes: 10, staffSkill: 'Beautician' },
  },
  {
    category: 'Threading & Waxing',
    name: 'Full Face Threading',
    sku: 'SAL-THRD-FACE',
    price: 250,
    costPrice: 50,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Eyebrow + upper lip + forehead threading',
    meta: { durationMinutes: 20, staffSkill: 'Beautician' },
  },
  {
    category: 'Threading & Waxing',
    name: 'Full Arms Waxing',
    sku: 'SAL-WAX-ARMS',
    price: 400,
    costPrice: 120,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Full arms waxing — both arms',
    meta: { durationMinutes: 25, staffSkill: 'Beautician' },
  },
  {
    category: 'Threading & Waxing',
    name: 'Full Legs Waxing',
    sku: 'SAL-WAX-LEGS',
    price: 600,
    costPrice: 180,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Full legs waxing — both legs',
    meta: { durationMinutes: 35, staffSkill: 'Beautician' },
  },
  {
    category: 'Threading & Waxing',
    name: 'Full Body Waxing',
    sku: 'SAL-WAX-FULL',
    price: 2500,
    costPrice: 750,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Complete full body waxing',
    meta: { durationMinutes: 90, staffSkill: 'Senior Beautician' },
  },

  // ── Beard & Men Grooming ──────────────────────────────────────────────────
  {
    category: 'Beard & Men Grooming',
    name: 'Beard Trim & Shape',
    sku: 'SAL-BEARD-TRIM',
    price: 200,
    costPrice: 40,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Beard trim + line-up + hot towel',
    meta: { durationMinutes: 20, staffSkill: 'Barber' },
  },
  {
    category: 'Beard & Men Grooming',
    name: 'Beard Colour',
    sku: 'SAL-BEARD-COLOR',
    price: 450,
    costPrice: 150,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Beard colouring with organic colour',
    meta: { durationMinutes: 30, staffSkill: 'Barber' },
  },
  {
    category: 'Beard & Men Grooming',
    name: 'Men\'s Facial – Basic',
    sku: 'SAL-MEN-FAC-BSC',
    price: 700,
    costPrice: 210,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Men\'s D-tan cleanup facial',
    meta: { durationMinutes: 45, staffSkill: 'Beautician' },
  },

  // ── Hair Products ─────────────────────────────────────────────────────────
  {
    category: 'Hair Products',
    name: 'Professional Shampoo – Keratin (250ml)',
    sku: 'SAL-SHMP-KER-250',
    price: 799,
    costPrice: 400,
    taxCode: '3305',
    unit: 'bottle',
    kind: 'physical',
    trackQty: true,
    qty: 30,
    brand: 'Wella',
    description: 'Keratin-infused strengthening shampoo',
    meta: { packSize: '250 ml', sellUnit: 'bottle' },
  },
  {
    category: 'Hair Products',
    name: 'Hair Conditioner – Colour Protect (200ml)',
    sku: 'SAL-COND-CP-200',
    price: 649,
    costPrice: 325,
    taxCode: '3305',
    unit: 'bottle',
    kind: 'physical',
    trackQty: true,
    qty: 25,
    brand: 'Matrix',
    description: 'Colour-safe daily conditioner',
    meta: { packSize: '200 ml', sellUnit: 'bottle' },
  },
  {
    category: 'Hair Products',
    name: 'Hair Serum – Anti-Frizz (100ml)',
    sku: 'SAL-SERUM-AF-100',
    price: 899,
    costPrice: 450,
    taxCode: '3305',
    unit: 'bottle',
    kind: 'physical',
    trackQty: true,
    qty: 20,
    brand: 'L\'Oréal',
    description: 'Shine-boosting anti-frizz hair serum',
    meta: { packSize: '100 ml', sellUnit: 'bottle' },
  },
  {
    category: 'Hair Products',
    name: 'Hair Oil – Argan (100ml)',
    sku: 'SAL-OIL-ARG-100',
    price: 599,
    costPrice: 300,
    taxCode: '1515',
    unit: 'bottle',
    kind: 'physical',
    trackQty: true,
    qty: 25,
    brand: 'OGX',
    description: 'Moroccan argan oil for deep nourishment',
    meta: { packSize: '100 ml', sellUnit: 'bottle' },
  },
  {
    category: 'Hair Products',
    name: 'Hair Mask – Protein Repair (200g)',
    sku: 'SAL-MASK-PR-200',
    price: 749,
    costPrice: 375,
    taxCode: '3305',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 15,
    brand: 'Schwarzkopf',
    description: 'Intense protein hair repair mask',
    meta: { packSize: '200 g', sellUnit: 'pcs' },
  },

  // ── Skin Products ─────────────────────────────────────────────────────────
  {
    category: 'Skin Products',
    name: 'Vitamin C Face Wash (100ml)',
    sku: 'SAL-FW-VC-100',
    price: 449,
    costPrice: 225,
    taxCode: '3304',
    unit: 'bottle',
    kind: 'physical',
    trackQty: true,
    qty: 25,
    brand: 'Neutrogena',
    description: 'Brightening vitamin C face wash',
    meta: { packSize: '100 ml', sellUnit: 'bottle' },
  },
  {
    category: 'Skin Products',
    name: 'Sunscreen SPF 50 (60ml)',
    sku: 'SAL-SUN-SPF50-60',
    price: 549,
    costPrice: 275,
    taxCode: '3304',
    unit: 'bottle',
    kind: 'physical',
    trackQty: true,
    qty: 30,
    brand: 'Lakme',
    description: 'Lightweight SPF 50 daily sunscreen',
    meta: { packSize: '60 ml', spf: 50, sellUnit: 'bottle' },
  },
  {
    category: 'Skin Products',
    name: 'Moisturizer – Day Cream (50ml)',
    sku: 'SAL-MOIST-DAY-50',
    price: 699,
    costPrice: 350,
    taxCode: '3304',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 20,
    brand: 'Olay',
    description: 'Lightweight non-greasy day moisturizer',
    meta: { packSize: '50 ml', sellUnit: 'pcs' },
  },

  // ── Accessories ───────────────────────────────────────────────────────────
  {
    category: 'Accessories',
    name: 'Hair Clips Set (10-pack)',
    sku: 'SAL-CLIPS-10',
    price: 199,
    costPrice: 75,
    taxCode: '9615',
    unit: 'pack',
    kind: 'physical',
    trackQty: true,
    qty: 30,
    description: 'Assorted salon-quality hair clips',
    meta: { count: 10, sellUnit: 'pack' },
  },
  {
    category: 'Accessories',
    name: 'Headband – Soft Cotton',
    sku: 'SAL-HEADBAND-01',
    price: 99,
    costPrice: 35,
    taxCode: '6117',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 40,
    description: 'Soft cotton facial spa headband',
  },
  {
    category: 'Accessories',
    name: 'Nail Polish – Red (Essie)',
    sku: 'SAL-NPLSH-RED',
    price: 599,
    costPrice: 300,
    taxCode: '3304',
    unit: 'bottle',
    kind: 'physical',
    trackQty: true,
    qty: 15,
    brand: 'Essie',
    description: 'Long-lasting red nail lacquer',
    meta: { color: 'Red', sellUnit: 'bottle' },
  },
];

export const SALON_CUSTOMERS = [
  { name: 'Anita Kapoor', phone: '9705000001', email: 'anita@salon.demo', meta: {} },
  { name: 'Bhavini Shah', phone: '9705000002', email: 'bhavini@salon.demo', meta: {} },
  { name: 'Charu Gupta', phone: '9705000003', email: 'charu@salon.demo', meta: {} },
  { name: 'Divya Menon', phone: '9705000004', email: 'divya@salon.demo', meta: {} },
  { name: 'Esha Reddy', phone: '9705000005', email: 'esha@salon.demo', meta: {} },
  { name: 'Farah Khan', phone: '9705000006', email: 'farah@salon.demo', meta: {} },
  { name: 'Gayatri Nair', phone: '9705000007', email: 'gayatri@salon.demo', meta: {} },
  { name: 'Hina Bose', phone: '9705000008', email: 'hina@salon.demo', meta: {} },
  { name: 'Ira Joshi', phone: '9705000009', email: 'ira@salon.demo', meta: {} },
  { name: 'Jinal Desai', phone: '9705000010', email: 'jinal@salon.demo', meta: {} },
  { name: 'Kinjal Trivedi', phone: '9705000011', email: 'kinjal@salon.demo', meta: {} },
  { name: 'Lavanya Pillai', phone: '9705000012', email: 'lavanya@salon.demo', meta: {} },
  { name: 'Meenakshi Rajan', phone: '9705000013', email: 'meenakshi@salon.demo', meta: {} },
  { name: 'Namrata Singh', phone: '9705000014', email: 'namrata@salon.demo', meta: {} },
  { name: 'Ojal Parikh', phone: '9705000015', email: 'ojal@salon.demo', meta: {} },
  { name: 'Parul Mehta', phone: '9705000016', email: 'parul@salon.demo', meta: {} },
  { name: 'Rachna Bajaj', phone: '9705000017', email: 'rachna@salon.demo', meta: {} },
  { name: 'Savita Rani', phone: '9705000018', email: 'savita@salon.demo', meta: {} },
  { name: 'Tanya Khanna', phone: '9705000019', email: 'tanya@salon.demo', meta: {} },
  { name: 'Walk-in Guest', phone: '9705000020', email: null, meta: {} },
];

export const SALON_STAFF = [
  { email: 'salon.manager@salon.demo', fullName: 'Salon Manager', role: 'manager', code: 'SL002' },
  { email: 'salon.staff@salon.demo', fullName: 'Salon Cashier', role: 'cashier', code: 'SL003' },
];

export const SALON_SUPPLIERS = [
  { code: 'SUP-SAL-001', name: 'Wella Professional Distributors', supplierType: 'distributor', contact: 'Ajay Hair', phone: '9900005001', email: 'supply@welladist.demo', paymentTerm: 'net_30', dueDays: 30, creditLimit: 300000 },
  { code: 'SUP-SAL-002', name: 'L\'Oréal Salon Direct', supplierType: 'manufacturer', contact: 'Sunita Beauty', phone: '9900005002', email: 'supply@loreal.demo', paymentTerm: 'net_30', dueDays: 30, creditLimit: 400000 },
  { code: 'SUP-SAL-003', name: 'Beauty Wholesale Hub', supplierType: 'wholesaler', contact: 'Prerna Das', phone: '9900005003', email: 'supply@beautyhub.demo', paymentTerm: 'net_15', dueDays: 15, creditLimit: 200000 },
  { code: 'SUP-SAL-004', name: 'Cosmetic Supplies India', supplierType: 'wholesaler', contact: 'Ritu Sharma', phone: '9900005004', email: 'supply@cosmsup.demo', paymentTerm: 'net_30', dueDays: 30, creditLimit: 150000 },
  { code: 'SUP-SAL-005', name: 'Nail & Skin Trade Co', supplierType: 'wholesaler', contact: 'Vandana Mehta', phone: '9900005005', email: 'supply@nailskin.demo', paymentTerm: 'net_30', dueDays: 30, creditLimit: 100000 },
];
