/**
 * Swimming Academy / Pool — 50 realistic items.
 * Business type: coaching (subscription + service modes).
 * Pure data — no business-type conditionals.
 */

export type CatalogItem = {
  category: string;
  name: string;
  sku: string;
  price: number;
  costPrice: number;
  taxCode: string;
  unit: string;
  kind: 'physical' | 'service';
  trackQty: boolean;
  qty: number;
  brand?: string;
  description?: string;
  meta?: Record<string, unknown>;
};

export const SWIMMING_CATEGORIES = [
  'Membership Plans',
  'Coaching Packages',
  'Group Classes',
  'Private Coaching',
  'Pool Access',
  'Swimming Accessories',
  'Swimwear',
  'Training Gear',
  'Other Services',
];

export const SWIMMING_PRODUCTS: CatalogItem[] = [
  // ── Membership Plans ──────────────────────────────────────────────────────
  {
    category: 'Membership Plans',
    name: 'Monthly Pool Membership – Morning Batch',
    sku: 'SWM-MEM-MOR-1M',
    price: 1800,
    costPrice: 360,
    taxCode: '9997',
    unit: 'month',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: '6:00–8:00 AM batch — 30 days',
    meta: { durationDays: 30, batchTime: 'Morning 6:00-8:00 AM', membershipTier: 'pool_access' },
  },
  {
    category: 'Membership Plans',
    name: 'Monthly Pool Membership – Evening Batch',
    sku: 'SWM-MEM-EVE-1M',
    price: 1600,
    costPrice: 320,
    taxCode: '9997',
    unit: 'month',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: '5:00–7:00 PM batch — 30 days',
    meta: { durationDays: 30, batchTime: 'Evening 5:00-7:00 PM', membershipTier: 'pool_access' },
  },
  {
    category: 'Membership Plans',
    name: 'Quarterly Pool Membership',
    sku: 'SWM-MEM-3M',
    price: 4800,
    costPrice: 960,
    taxCode: '9997',
    unit: 'quarter',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Unlimited pool access — 90 days',
    meta: { durationDays: 90, membershipTier: 'pool_access' },
  },
  {
    category: 'Membership Plans',
    name: 'Half-Year Pool Membership',
    sku: 'SWM-MEM-6M',
    price: 8500,
    costPrice: 1700,
    taxCode: '9997',
    unit: 'period',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Unlimited pool access — 180 days',
    meta: { durationDays: 180, membershipTier: 'pool_access' },
  },
  {
    category: 'Membership Plans',
    name: 'Annual Pool Membership – Standard',
    sku: 'SWM-MEM-1Y',
    price: 15000,
    costPrice: 3000,
    taxCode: '9997',
    unit: 'year',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Unlimited pool access — 365 days',
    meta: { durationDays: 365, membershipTier: 'pool_access' },
  },
  {
    category: 'Membership Plans',
    name: 'Annual Pool Membership – Premium (Locker + Towel)',
    sku: 'SWM-MEM-PRM-1Y',
    price: 20000,
    costPrice: 4000,
    taxCode: '9997',
    unit: 'year',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Unlimited + locker + towel — 365 days',
    meta: { durationDays: 365, membershipTier: 'premium', includesLocker: true, includesTowel: true },
  },
  {
    category: 'Membership Plans',
    name: 'Kids Monthly Membership (Under 12)',
    sku: 'SWM-MEM-KIDS-1M',
    price: 1200,
    costPrice: 240,
    taxCode: '9997',
    unit: 'month',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Supervised kids pool session — 30 days',
    meta: { durationDays: 30, ageGroup: 'under_12', membershipTier: 'kids' },
  },
  {
    category: 'Membership Plans',
    name: 'Senior Citizen Monthly (60+)',
    sku: 'SWM-MEM-SR-1M',
    price: 1000,
    costPrice: 200,
    taxCode: '9997',
    unit: 'month',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Senior aqua therapy and leisure swimming — 30 days',
    meta: { durationDays: 30, ageGroup: '60+', membershipTier: 'senior' },
  },
  {
    category: 'Membership Plans',
    name: 'Family Package – Monthly (4 members)',
    sku: 'SWM-MEM-FAM-1M',
    price: 5500,
    costPrice: 1100,
    taxCode: '9997',
    unit: 'month',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Up to 4 family members — 30 days',
    meta: { durationDays: 30, seats: 4, membershipTier: 'family' },
  },
  {
    category: 'Membership Plans',
    name: 'Day Pass – Walk-In',
    sku: 'SWM-DAYPASS',
    price: 250,
    costPrice: 50,
    taxCode: '9997',
    unit: 'day',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Single-day pool access',
    meta: { durationDays: 1 },
  },

  // ── Coaching Packages ─────────────────────────────────────────────────────
  {
    category: 'Coaching Packages',
    name: 'Beginner Swimming Course – 1 Month',
    sku: 'SWM-COACH-BEG-1M',
    price: 3500,
    costPrice: 1750,
    taxCode: '9997',
    unit: 'package',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: '16 sessions — water confidence to basic strokes',
    meta: { sessions: 16, durationDays: 30, level: 'beginner', staffSkill: 'Swimming Coach' },
  },
  {
    category: 'Coaching Packages',
    name: 'Intermediate Swimming Course – 1 Month',
    sku: 'SWM-COACH-INT-1M',
    price: 4000,
    costPrice: 2000,
    taxCode: '9997',
    unit: 'package',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: '16 sessions — freestyle, backstroke improvement',
    meta: { sessions: 16, durationDays: 30, level: 'intermediate', staffSkill: 'Swimming Coach' },
  },
  {
    category: 'Coaching Packages',
    name: 'Advanced Swimming Course – 1 Month',
    sku: 'SWM-COACH-ADV-1M',
    price: 5000,
    costPrice: 2500,
    taxCode: '9997',
    unit: 'package',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: '16 sessions — butterfly, breaststroke, turns, dives',
    meta: { sessions: 16, durationDays: 30, level: 'advanced', staffSkill: 'Senior Coach' },
  },
  {
    category: 'Coaching Packages',
    name: 'Kids Learn to Swim – 1 Month',
    sku: 'SWM-COACH-KIDS-1M',
    price: 2800,
    costPrice: 1400,
    taxCode: '9997',
    unit: 'package',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: '16 supervised sessions — ages 5–12',
    meta: { sessions: 16, durationDays: 30, ageGroup: '5-12', staffSkill: 'Kids Coach' },
  },
  {
    category: 'Coaching Packages',
    name: 'Adult Beginner Course – 1 Month',
    sku: 'SWM-COACH-ADU-1M',
    price: 3800,
    costPrice: 1900,
    taxCode: '9997',
    unit: 'package',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: '16 sessions — adult non-swimmers to basic freestyle',
    meta: { sessions: 16, durationDays: 30, ageGroup: 'adult', level: 'beginner' },
  },
  {
    category: 'Coaching Packages',
    name: 'Competitive Swimming Training – Monthly',
    sku: 'SWM-COMP-1M',
    price: 8000,
    costPrice: 4000,
    taxCode: '9997',
    unit: 'month',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Intensive daily training for competitive swimmers',
    meta: { durationDays: 30, level: 'competitive', sessionsPerWeek: 6 },
  },
  {
    category: 'Coaching Packages',
    name: 'Aqua Aerobics – Monthly',
    sku: 'SWM-AQUA-1M',
    price: 2200,
    costPrice: 440,
    taxCode: '9997',
    unit: 'month',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Group aqua aerobics — 16 sessions',
    meta: { sessions: 16, durationDays: 30, classType: 'aqua_aerobics' },
  },

  // ── Private Coaching ──────────────────────────────────────────────────────
  {
    category: 'Private Coaching',
    name: 'Private Coaching – 1 Session',
    sku: 'SWM-PRIV-1S',
    price: 1500,
    costPrice: 750,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'One-on-one coaching — 45 minutes',
    meta: { durationMinutes: 45, staffSkill: 'Senior Coach' },
  },
  {
    category: 'Private Coaching',
    name: 'Private Coaching – 8 Session Pack',
    sku: 'SWM-PRIV-8S',
    price: 10000,
    costPrice: 5000,
    taxCode: '9997',
    unit: 'package',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: '8 × 45-min one-on-one sessions (valid 60 days)',
    meta: { sessions: 8, validDays: 60, staffSkill: 'Senior Coach' },
  },
  {
    category: 'Private Coaching',
    name: 'Semi-Private Coaching (2 students)',
    sku: 'SWM-SEMI-1S',
    price: 1000,
    costPrice: 500,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Shared coaching — 45 min, 2 students',
    meta: { durationMinutes: 45, maxStudents: 2 },
  },

  // ── Group Classes ─────────────────────────────────────────────────────────
  {
    category: 'Group Classes',
    name: 'Weekend Batch – Morning (6-week)',
    sku: 'SWM-WKD-6W',
    price: 4500,
    costPrice: 900,
    taxCode: '9997',
    unit: 'package',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: '12 sessions on Sat-Sun — 6 weeks',
    meta: { sessions: 12, durationDays: 42, batchTime: 'Weekend AM' },
  },
  {
    category: 'Group Classes',
    name: 'Summer Intensive Camp – 4 Weeks',
    sku: 'SWM-CAMP-4W',
    price: 6000,
    costPrice: 1200,
    taxCode: '9997',
    unit: 'package',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Daily summer camp — 24 sessions over 4 weeks',
    meta: { sessions: 24, durationDays: 28, classType: 'summer_camp' },
  },
  {
    category: 'Group Classes',
    name: 'Water Safety Workshop – 1 Day',
    sku: 'SWM-WSW-1D',
    price: 1000,
    costPrice: 200,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Emergency water safety and rescue skills',
    meta: { durationMinutes: 180, classType: 'safety_workshop' },
  },

  // ── Pool Access ───────────────────────────────────────────────────────────
  {
    category: 'Pool Access',
    name: 'Open Swim – 1 Hour (Casual)',
    sku: 'SWM-OPEN-1HR',
    price: 150,
    costPrice: 30,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Casual 1-hour pool access slot',
    meta: { durationMinutes: 60 },
  },
  {
    category: 'Pool Access',
    name: 'Lane Rental – 1 Hour (Club/School)',
    sku: 'SWM-LANE-1HR',
    price: 800,
    costPrice: 160,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Exclusive lane for clubs or schools — 1 hour',
    meta: { durationMinutes: 60, type: 'lane_rental' },
  },
  {
    category: 'Pool Access',
    name: 'Locker – Monthly Rental',
    sku: 'SWM-LOCK-1M',
    price: 500,
    costPrice: 100,
    taxCode: '9972',
    unit: 'month',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Dedicated locker for 30 days',
    meta: { durationDays: 30 },
  },
  {
    category: 'Pool Access',
    name: 'Towel Service – Monthly',
    sku: 'SWM-TOWEL-1M',
    price: 300,
    costPrice: 60,
    taxCode: '9997',
    unit: 'month',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Fresh towel each visit for 30 days',
    meta: { durationDays: 30 },
  },

  // ── Swimming Accessories ──────────────────────────────────────────────────
  {
    category: 'Swimming Accessories',
    name: 'Swim Goggles – Anti-Fog (Adult)',
    sku: 'SWM-GOG-AD',
    price: 499,
    costPrice: 200,
    taxCode: '9506',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 40,
    brand: 'Speedo',
    description: 'UV-protection anti-fog swim goggles',
    meta: { ageGroup: 'adult' },
  },
  {
    category: 'Swimming Accessories',
    name: 'Swim Goggles – Kids',
    sku: 'SWM-GOG-KID',
    price: 299,
    costPrice: 120,
    taxCode: '9506',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 30,
    brand: 'Speedo',
    description: 'Colourful kids swim goggles with adjustable strap',
    meta: { ageGroup: 'kids' },
  },
  {
    category: 'Swimming Accessories',
    name: 'Swim Cap – Silicone',
    sku: 'SWM-CAP-SIL',
    price: 199,
    costPrice: 75,
    taxCode: '6117',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 50,
    brand: 'Arena',
    description: 'Durable silicone swim cap — universal fit',
  },
  {
    category: 'Swimming Accessories',
    name: 'Swim Fins – Training (Pair)',
    sku: 'SWM-FINS-PR',
    price: 699,
    costPrice: 280,
    taxCode: '9506',
    unit: 'pair',
    kind: 'physical',
    trackQty: true,
    qty: 20,
    brand: 'Speedo',
    description: 'Short blade training fins for kick improvement',
    meta: { size: 'M/L' },
  },
  {
    category: 'Swimming Accessories',
    name: 'Kickboard – Foam',
    sku: 'SWM-KICK-01',
    price: 349,
    costPrice: 140,
    taxCode: '9506',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 25,
    brand: 'Arena',
    description: 'EVA foam kickboard for stroke drills',
  },
  {
    category: 'Swimming Accessories',
    name: 'Pull Buoy',
    sku: 'SWM-BUOY-01',
    price: 299,
    costPrice: 120,
    taxCode: '9506',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 25,
    brand: 'Arena',
    description: 'Figure-8 pull buoy for arm stroke training',
  },
  {
    category: 'Swimming Accessories',
    name: 'Hand Paddles – Training',
    sku: 'SWM-PADDLE-01',
    price: 499,
    costPrice: 200,
    taxCode: '9506',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 20,
    brand: 'Speedo',
    description: 'Contoured hand paddles for stroke resistance training',
    meta: { size: 'M' },
  },
  {
    category: 'Swimming Accessories',
    name: 'Nose Clip',
    sku: 'SWM-NOSECLIP-01',
    price: 99,
    costPrice: 35,
    taxCode: '9506',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 60,
    brand: 'Speedo',
    description: 'Stainless steel nose clip with soft pads',
  },
  {
    category: 'Swimming Accessories',
    name: 'Ear Plugs – Swimming (Pair)',
    sku: 'SWM-EARPLUG-PR',
    price: 79,
    costPrice: 30,
    taxCode: '9506',
    unit: 'pair',
    kind: 'physical',
    trackQty: true,
    qty: 80,
    description: 'Soft silicone swimming ear plugs',
  },

  // ── Swimwear ──────────────────────────────────────────────────────────────
  {
    category: 'Swimwear',
    name: 'Swim Trunks – Men (M)',
    sku: 'SWM-TRUNK-M',
    price: 699,
    costPrice: 280,
    taxCode: '6211',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 20,
    brand: 'Speedo',
    description: 'Chlorine-resistant brief-style trunks',
    meta: { size: 'M', gender: 'M' },
  },
  {
    category: 'Swimwear',
    name: 'One-Piece Swimsuit – Women (M)',
    sku: 'SWM-SWIM-WM-M',
    price: 999,
    costPrice: 400,
    taxCode: '6211',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 15,
    brand: 'Arena',
    description: 'Chlorine-resistant training swimsuit',
    meta: { size: 'M', gender: 'F' },
  },
  {
    category: 'Swimwear',
    name: 'Kids Swimsuit (Unisex, Size 8)',
    sku: 'SWM-SWIM-KID-8',
    price: 499,
    costPrice: 200,
    taxCode: '6111',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 18,
    brand: 'Speedo',
    description: 'Quick-dry kids swimsuit — size 8',
    meta: { size: '8', ageGroup: 'kids' },
  },
  {
    category: 'Swimwear',
    name: 'Rash Guard – Long Sleeve (M)',
    sku: 'SWM-RASH-M',
    price: 799,
    costPrice: 320,
    taxCode: '6211',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 12,
    brand: 'Decathlon',
    description: 'UPF 50+ rash guard for pool or open water',
    meta: { size: 'M', upf: 50 },
  },

  // ── Training Gear ─────────────────────────────────────────────────────────
  {
    category: 'Training Gear',
    name: 'Waterproof Sports Watch',
    sku: 'SWM-WATCH-WP',
    price: 2999,
    costPrice: 1500,
    taxCode: '9102',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 8,
    brand: 'Garmin',
    description: 'Lap counter + heart rate — 50m waterproof',
  },
  {
    category: 'Training Gear',
    name: 'Swimming Resistance Belt',
    sku: 'SWM-RESBELT-01',
    price: 1200,
    costPrice: 500,
    taxCode: '9506',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 10,
    description: 'Stationary resistance belt for in-place swimming training',
  },
  {
    category: 'Training Gear',
    name: 'Underwater Earphones',
    sku: 'SWM-EARPH-UW',
    price: 2499,
    costPrice: 1200,
    taxCode: '8518',
    unit: 'pcs',
    kind: 'physical',
    trackQty: true,
    qty: 5,
    brand: 'H2O Audio',
    description: 'Waterproof swimming earphones — IPX8',
  },

  // ── Other Services ────────────────────────────────────────────────────────
  {
    category: 'Other Services',
    name: 'Pool Party Package – 2 Hours',
    sku: 'SWM-PARTY-2H',
    price: 8000,
    costPrice: 2000,
    taxCode: '9997',
    unit: 'event',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Exclusive pool hire for private party — up to 20 guests',
    meta: { durationMinutes: 120, maxGuests: 20 },
  },
  {
    category: 'Other Services',
    name: 'Physiotherapy Session (Aqua)',
    sku: 'SWM-PHYSIO-1S',
    price: 1800,
    costPrice: 900,
    taxCode: '9997',
    unit: 'session',
    kind: 'service',
    trackQty: false,
    qty: 0,
    description: 'Aquatic physiotherapy for injury rehab — 1 hour',
    meta: { durationMinutes: 60, staffSkill: 'Aqua Physiotherapist' },
  },
];

export const SWIMMING_CUSTOMERS = [
  { name: 'Aakash Mehta', phone: '9704000001', email: 'aakash@swimming.demo', meta: { fitnessGoal: 'Fitness swimming' } },
  { name: 'Bindiya Shah', phone: '9704000002', email: 'bindiya@swimming.demo', meta: { fitnessGoal: 'Competition' } },
  { name: 'Chirag Patel', phone: '9704000003', email: 'chirag@swimming.demo', meta: {} },
  { name: 'Disha Kapoor', phone: '9704000004', email: 'disha@swimming.demo', meta: { fitnessGoal: 'Water fitness' } },
  { name: 'Ekta Rao', phone: '9704000005', email: 'ekta@swimming.demo', meta: {} },
  { name: 'Farida Banu', phone: '9704000006', email: 'farida@swimming.demo', meta: { fitnessGoal: 'Therapy' } },
  { name: 'Gaurav Joshi', phone: '9704000007', email: 'gaurav@swimming.demo', meta: {} },
  { name: 'Harsha Nair', phone: '9704000008', email: 'harsha@swimming.demo', meta: { fitnessGoal: 'Learn to swim' } },
  { name: 'Isha Kumar', phone: '9704000009', email: 'isha@swimming.demo', meta: {} },
  { name: 'Jai Pandey', phone: '9704000010', email: 'jai@swimming.demo', meta: {} },
  { name: 'Kiran Desai', phone: '9704000011', email: 'kiran@swimming.demo', meta: { fitnessGoal: 'Kids class' } },
  { name: 'Lalitha Reddy', phone: '9704000012', email: 'lalitha@swimming.demo', meta: {} },
  { name: 'Mohan Iyer', phone: '9704000013', email: 'mohan@swimming.demo', meta: { fitnessGoal: 'Senior fitness' } },
  { name: 'Nalini Bose', phone: '9704000014', email: 'nalini@swimming.demo', meta: {} },
  { name: 'Om Prakash', phone: '9704000015', email: 'om@swimming.demo', meta: {} },
  { name: 'Padmavathi G', phone: '9704000016', email: 'padmavathi@swimming.demo', meta: { fitnessGoal: 'Aqua aerobics' } },
  { name: 'Raj Malhotra', phone: '9704000017', email: 'raj@swimming.demo', meta: {} },
  { name: 'Sunita Verma', phone: '9704000018', email: 'sunita@swimming.demo', meta: {} },
  { name: 'Tarun Singh', phone: '9704000019', email: 'tarun@swimming.demo', meta: { fitnessGoal: 'Competition' } },
  { name: 'Walk-in Guest', phone: '9704000020', email: null, meta: {} },
];

export const SWIMMING_STAFF = [
  { email: 'swimming.manager@swimming.demo', fullName: 'Pool Manager', role: 'manager', code: 'SW002' },
  { email: 'swimming.staff@swimming.demo', fullName: 'Pool Staff', role: 'cashier', code: 'SW003' },
];

export const SWIMMING_SUPPLIERS = [
  { code: 'SUP-SWM-001', name: 'Speedo India Distributors', supplierType: 'distributor', contact: 'Rohan Swim', phone: '9900004001', email: 'supply@speedodist.demo', paymentTerm: 'net_30', dueDays: 30, creditLimit: 300000 },
  { code: 'SUP-SWM-002', name: 'Arena Sports India', supplierType: 'distributor', contact: 'Neha Aqua', phone: '9900004002', email: 'supply@arenasports.demo', paymentTerm: 'net_30', dueDays: 30, creditLimit: 200000 },
  { code: 'SUP-SWM-003', name: 'Pool & Fitness Wholesale', supplierType: 'wholesaler', contact: 'Kumar Pool', phone: '9900004003', email: 'supply@poolfitness.demo', paymentTerm: 'net_15', dueDays: 15, creditLimit: 150000 },
];
