import { GlAccountType } from '@prisma/client';
import { MAP, type MappingKey } from './constants';

export type ChartTemplateAccount = {
  code: string;
  name: string;
  type: GlAccountType;
  subtype: string;
  category: string;
  parentCode?: string;
  mappingKeys?: MappingKey[];
};

/**
 * Default Chart of Accounts seeded when accounting is first enabled.
 * Accounts remain editable — this is a template, not a hardcoded runtime CoA.
 */
export const DEFAULT_CHART_TEMPLATE: ChartTemplateAccount[] = [
  { code: '1000', name: 'Assets', type: 'ASSET', subtype: 'CURRENT_ASSET', category: 'Assets' },
  {
    code: '1010',
    name: 'Cash',
    type: 'ASSET',
    subtype: 'CURRENT_ASSET',
    category: 'Cash',
    parentCode: '1000',
    mappingKeys: [MAP.cash],
  },
  {
    code: '1020',
    name: 'Bank',
    type: 'ASSET',
    subtype: 'CURRENT_ASSET',
    category: 'Bank',
    parentCode: '1000',
    mappingKeys: [MAP.bank],
  },
  {
    code: '1030',
    name: 'UPI',
    type: 'ASSET',
    subtype: 'CURRENT_ASSET',
    category: 'UPI',
    parentCode: '1000',
    mappingKeys: [MAP.upi],
  },
  {
    code: '1040',
    name: 'Card clearing',
    type: 'ASSET',
    subtype: 'CURRENT_ASSET',
    category: 'Card',
    parentCode: '1000',
    mappingKeys: [MAP.card],
  },
  {
    code: '1050',
    name: 'Wallet',
    type: 'ASSET',
    subtype: 'CURRENT_ASSET',
    category: 'Wallet',
    parentCode: '1000',
    mappingKeys: [MAP.wallet, MAP.other_tender],
  },
  {
    code: '1100',
    name: 'Accounts Receivable',
    type: 'ASSET',
    subtype: 'CURRENT_ASSET',
    category: 'Receivables',
    parentCode: '1000',
    mappingKeys: [MAP.ar],
  },
  {
    code: '1200',
    name: 'Inventory',
    type: 'ASSET',
    subtype: 'CURRENT_ASSET',
    category: 'Inventory',
    parentCode: '1000',
    mappingKeys: [MAP.inventory],
  },
  {
    code: '1300',
    name: 'Input GST',
    type: 'ASSET',
    subtype: 'CURRENT_ASSET',
    category: 'Tax',
    parentCode: '1000',
    mappingKeys: [MAP.input_gst, MAP.input_cgst, MAP.input_sgst, MAP.input_igst],
  },
  { code: '1500', name: 'Fixed assets', type: 'ASSET', subtype: 'FIXED_ASSET', category: 'Fixed assets' },
  { code: '2000', name: 'Liabilities', type: 'LIABILITY', subtype: 'CURRENT_LIABILITY', category: 'Liabilities' },
  {
    code: '2010',
    name: 'Accounts Payable',
    type: 'LIABILITY',
    subtype: 'CURRENT_LIABILITY',
    category: 'Payables',
    parentCode: '2000',
    mappingKeys: [MAP.ap],
  },
  {
    code: '2100',
    name: 'Output GST',
    type: 'LIABILITY',
    subtype: 'CURRENT_LIABILITY',
    category: 'Tax',
    parentCode: '2000',
    mappingKeys: [MAP.output_gst, MAP.output_cgst, MAP.output_sgst, MAP.output_igst, MAP.output_cess],
  },
  {
    code: '2200',
    name: 'Customer advances',
    type: 'LIABILITY',
    subtype: 'CURRENT_LIABILITY',
    category: 'Advances',
    parentCode: '2000',
    mappingKeys: [MAP.customer_advances, MAP.deposits],
  },
  {
    code: '2300',
    name: 'Gift cards & store credit',
    type: 'LIABILITY',
    subtype: 'CURRENT_LIABILITY',
    category: 'Advances',
    parentCode: '2000',
    mappingKeys: [MAP.gift_card, MAP.store_credit],
  },
  { code: '2500', name: 'Long-term liabilities', type: 'LIABILITY', subtype: 'LONG_TERM_LIABILITY', category: 'Long-term' },
  { code: '3000', name: 'Equity', type: 'EQUITY', subtype: 'EQUITY', category: 'Equity' },
  {
    code: '3010',
    name: 'Owner capital',
    type: 'EQUITY',
    subtype: 'EQUITY',
    category: 'Equity',
    parentCode: '3000',
  },
  {
    code: '3100',
    name: 'Retained earnings',
    type: 'EQUITY',
    subtype: 'EQUITY',
    category: 'Equity',
    parentCode: '3000',
    mappingKeys: [MAP.retained_earnings],
  },
  { code: '4000', name: 'Revenue', type: 'REVENUE', subtype: 'REVENUE', category: 'Revenue' },
  {
    code: '4010',
    name: 'Product sales',
    type: 'REVENUE',
    subtype: 'REVENUE',
    category: 'Sales',
    parentCode: '4000',
    mappingKeys: [MAP.sales],
  },
  {
    code: '4020',
    name: 'Service revenue',
    type: 'REVENUE',
    subtype: 'REVENUE',
    category: 'Sales',
    parentCode: '4000',
    mappingKeys: [MAP.service_revenue],
  },
  {
    code: '4030',
    name: 'Rental revenue',
    type: 'REVENUE',
    subtype: 'REVENUE',
    category: 'Sales',
    parentCode: '4000',
    mappingKeys: [MAP.rental_revenue],
  },
  {
    code: '4040',
    name: 'Subscription revenue',
    type: 'REVENUE',
    subtype: 'REVENUE',
    category: 'Sales',
    parentCode: '4000',
    mappingKeys: [MAP.subscription_revenue],
  },
  {
    code: '4100',
    name: 'Sales returns',
    type: 'REVENUE',
    subtype: 'CONTRA_REVENUE',
    category: 'Returns',
    parentCode: '4000',
    mappingKeys: [MAP.sales_return],
  },
  {
    code: '4200',
    name: 'Discounts',
    type: 'REVENUE',
    subtype: 'CONTRA_REVENUE',
    category: 'Returns',
    parentCode: '4000',
    mappingKeys: [MAP.discounts],
  },
  { code: '5000', name: 'Expenses', type: 'EXPENSE', subtype: 'OPERATING_EXPENSE', category: 'Expenses' },
  {
    code: '5010',
    name: 'Cost of goods sold',
    type: 'EXPENSE',
    subtype: 'COGS',
    category: 'COGS',
    parentCode: '5000',
    mappingKeys: [MAP.cogs],
  },
  {
    code: '5020',
    name: 'Purchases',
    type: 'EXPENSE',
    subtype: 'COGS',
    category: 'Purchases',
    parentCode: '5000',
    mappingKeys: [MAP.purchase],
  },
  {
    code: '5030',
    name: 'Purchase returns',
    type: 'EXPENSE',
    subtype: 'COGS',
    category: 'Purchases',
    parentCode: '5000',
    mappingKeys: [MAP.purchase_return],
  },
  {
    code: '5100',
    name: 'Operating expenses',
    type: 'EXPENSE',
    subtype: 'OPERATING_EXPENSE',
    category: 'Opex',
    parentCode: '5000',
    mappingKeys: [MAP.expense_default],
  },
];
